language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: szeyick-github
    token:
      secure: fvAuulAWtW1/wbm8sVWJdsdNBYZW7Uxp8W0D8lenbBY9kfazyFF3HgzkN28TAEIMHWP8hLv3OBemxaYivI+SaXTjTRpGxD71VXa98C8Uca05jqr1RZMuWgwyya3aZP0lHY73DsuWm6L8Lz4F0AEkjRdf97idIKUbEYP9vQfQkuW1D5A8DEAFDSsIdEKgKZZXcfMjFwoHI40dePT6LXJCjMIYnWh9riK921O1nC+/PJrsuhg8KSp4kekBqTC5oXPnXBHtHdsuLrVfwqniwR9dc2W9klKuhlETER5jrjyq4jUUAYBK52NiaJzXdqtiQkhBr4EVltsNP26vXfVAsf5DmO5sEA/bOc5ab+CMkWX3PZucL8yBhQ87AxEaBP3X7qF5oOvU7VYyQxrGtyoz9RouxfJ6YdON0XfKJtNK1amh7ucYc25gG73HlJoM3tCa+1JR2XMdVnvrTrjL4Z+SPFC9hfSeBJHAroDaIkxGg+PUOQoUi2CqO7+jTqHi8papb4MLc4Mwf5IiMEtpOYRq/wZLxZ8NAYfIG6ghPDXleiPrKVtykBG/2WC5anUUF0Z2sptrJfeJEwWcC7TEeDlw/pNizFR4tgxqqGekNr/EMUVqJOqSSeAAkHNSLjTlyQjTaO2554cN99XsaFJrXrQNefvZn/lxSzkB0iafSpWyK+AP/wg=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
